apiVersion: v1
kind: Service
metadata:
  name: postgres-headless-service
  namespace: cinema-mk-namespace
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - port: 4422
      targetPort: 6060
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: cinema-mk-namespace
data:
  #POSTGRES_HOST: postgres-headless-service # Use the service name
  POSTGRES_PORT: "6060" # Default PostgreSQL port
  POSTGRES_DB: cinema-mk
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: sofe1243
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-headless-service:6060/cinema-mk
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_PASSWORD: c29mZTEyNDM=  #<base64-encoded-password>

